### PR TITLE
Add some preliminary documentation.

### PR DESCRIPTION
**Pull request by steowens**
This is a little toungue in cheek but I figured it would be good to get the ball rolling on documenting salmon, and along the way document potential new user pain points.

### CODE REVIEW

**Comment by moggers87** [comment]
Thanks for this, looks good!

I'll merge once the diff is sorted out.

**Comment by steowens** [comment]
Are there any further steps you need me to take?

**Comment by moggers87** [comment]
You still haven't fixed `README.md`. The file was originally using CRLF line terminators and you've changed those to LFs (good!). However, you've done that in the same commit as you've added your other changes (bad!).

**Comment by moggers87** [comment]
Closing as we now have some (incomplete) Sphinx docs in master

**Pull request closed without merging**
