### PR TITLE
Python 3 support

### LINKED ISSUE #7: Python 3 support
Python 3 support would be a great selling point

### PR DESCRIPTION
**Pull request by moggers87**
Fixes #7

* Try to avoid easy_install
* Remove win32 "support" - it was untested and couldn't be used in
  production anyway.
* Mock chardet rather than the string object
* Don't use reserved words
* Do binary file reading properly
* SMTPD messages are slightly different between Python 2 and 3
* Put test states.db in a folder that gets cleaned between test runs
* Depending on what version of Python we're using, `reload` could in one
  of three places.
* Use more modern try: except: syntax
* Print is a function in Python 3

### CODE REVIEW

**Comment by moggers87** [comment]
There's one failing test, and then I'm ready to merge this, even if Python 3 support is only "experimental"

**Comment by Juanlu001** [comment]
Hi! Do you need help to finish this up?

**Comment by moggers87** [comment]
It needs testing with a proper app before merging. I don't trust the unit tests quite enough to go ahead and merge these changes.

**Comment by moggers87** [comment]
As I suspected:

```
2017-11-03 21:00:22,929 - root - DEBUG - Message received from Peer: ('127.0.0.1', 49112), From: b'me@example.com', to To b'you@example.com'.
2017-11-03 21:00:22,929 - root - ERROR - Exception while processing message from Peer: ('127.0.0.1', 49112), From: b'me@example.com', to To b'you@example.com'.
Traceback (most recent call last):                                  
  File "/home/moggers/workspace/inboxen/salmon/py3-env/lib/python3.6/site-packages/salmon_mail-2.99.99-py3.6.egg/salmon/server.py", line 289, in process_message
    routing.Router.deliver(mail.MailRequest(Peer, From, To, Data))  
  File "/home/moggers/workspace/inboxen/salmon/py3-env/lib/python3.6/site-packages/salmon_mail-2.99.99-py3.6.egg/salmon/mail.py", line 64, in __init__
    self.From = _decode_header_randomness(From).pop()               
  File "/home/moggers/workspace/inboxen/salmon/py3-env/lib/python3.6/site-packages/salmon_mail-2.99.99-py3.6.egg/salmon/mail.py", line 40, in _decode_header_randomness
    raise encoding.EncodingError("Address must be a string or a list not: %r", type(addr))                                              
salmon.encoding.EncodingError: ('Address must be a string or a list not: %r', <class 'bytes'>)                                          
2017-11-03 21:00:22,945 - root - ERROR - Failed to deliver message because of "Error in message ('127.0.0.1', 49112):b'me@example.com':b'you@example.com', look in logs.", put it in undeliverable queue with key '1509742822.M930561P1093Q1.youngteazer'
```

**Pull request merged**
